matrix:
  include:
    - os: linux
      language: node_js
      node_js:
        - 12
    - os: windows
      language: node_js
      node_js:
        - 12
    - os: osx
      language: node_js
      node_js:
        - 12
