matrix:
  include:
    - os: linux
      language: node_js
      node_js:
        - 12
      deploy:
        - provider: script
          script: echo $NPM_AUTH > ~/.npmrc && node publish
          skip_cleanup: true
          on:
            branch: master
    - os: windows
      language: node_js
      node_js:
        - 12
    - os: osx
      language: node_js
      node_js:
        - 12
